version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y maven

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
      # - npm test
  build:
    commands:
      - mvn install package 
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam package --s3-bucket lambdapipelinedemo --output-template-file target/packaged-template.yaml
artifacts:
  type: zip
  files:
    - packaged-template.yaml
    
    
    
