version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      #- apt-get update -y
      #- apt-get install -y maven
      
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade pip
      #- pip install --upgrade awscli
      - pip install --upgrade aws-sam-cli
  pre_build:
    commands:
      # Discover and run unit tests in the 'tests' directory
     
  build:
    commands:
      - mvn install package 
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sam package --s3-bucket harika-lambda-pipeline --output-template-file packaged-template.yaml
artifacts:
  type: zip
  files:
    - packaged-template.yaml
    
    
    
